/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.2
// source: task.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as task_pb from './task_pb'; // proto import: "task.proto"


export class TaskServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateTask = new grpcWeb.MethodDescriptor(
    '/TaskService/CreateTask',
    grpcWeb.MethodType.UNARY,
    task_pb.TaskRequest,
    task_pb.TaskResponse,
    (request: task_pb.TaskRequest) => {
      return request.serializeBinary();
    },
    task_pb.TaskResponse.deserializeBinary
  );

  createTask(
    request: task_pb.TaskRequest,
    metadata?: grpcWeb.Metadata | null): Promise<task_pb.TaskResponse>;

  createTask(
    request: task_pb.TaskRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: task_pb.TaskResponse) => void): grpcWeb.ClientReadableStream<task_pb.TaskResponse>;

  createTask(
    request: task_pb.TaskRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: task_pb.TaskResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/TaskService/CreateTask',
        request,
        metadata || {},
        this.methodDescriptorCreateTask,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/TaskService/CreateTask',
    request,
    metadata || {},
    this.methodDescriptorCreateTask);
  }

  methodDescriptorListTasks = new grpcWeb.MethodDescriptor(
    '/TaskService/ListTasks',
    grpcWeb.MethodType.UNARY,
    task_pb.Empty,
    task_pb.TaskListResponse,
    (request: task_pb.Empty) => {
      return request.serializeBinary();
    },
    task_pb.TaskListResponse.deserializeBinary
  );

  listTasks(
    request: task_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<task_pb.TaskListResponse>;

  listTasks(
    request: task_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: task_pb.TaskListResponse) => void): grpcWeb.ClientReadableStream<task_pb.TaskListResponse>;

  listTasks(
    request: task_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: task_pb.TaskListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/TaskService/ListTasks',
        request,
        metadata || {},
        this.methodDescriptorListTasks,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/TaskService/ListTasks',
    request,
    metadata || {},
    this.methodDescriptorListTasks);
  }

  methodDescriptorUpdateTask = new grpcWeb.MethodDescriptor(
    '/TaskService/UpdateTask',
    grpcWeb.MethodType.UNARY,
    task_pb.TaskRequest,
    task_pb.TaskResponse,
    (request: task_pb.TaskRequest) => {
      return request.serializeBinary();
    },
    task_pb.TaskResponse.deserializeBinary
  );

  updateTask(
    request: task_pb.TaskRequest,
    metadata?: grpcWeb.Metadata | null): Promise<task_pb.TaskResponse>;

  updateTask(
    request: task_pb.TaskRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: task_pb.TaskResponse) => void): grpcWeb.ClientReadableStream<task_pb.TaskResponse>;

  updateTask(
    request: task_pb.TaskRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: task_pb.TaskResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/TaskService/UpdateTask',
        request,
        metadata || {},
        this.methodDescriptorUpdateTask,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/TaskService/UpdateTask',
    request,
    metadata || {},
    this.methodDescriptorUpdateTask);
  }

  methodDescriptorDeleteTask = new grpcWeb.MethodDescriptor(
    '/TaskService/DeleteTask',
    grpcWeb.MethodType.UNARY,
    task_pb.TaskRequest,
    task_pb.TaskResponse,
    (request: task_pb.TaskRequest) => {
      return request.serializeBinary();
    },
    task_pb.TaskResponse.deserializeBinary
  );

  deleteTask(
    request: task_pb.TaskRequest,
    metadata?: grpcWeb.Metadata | null): Promise<task_pb.TaskResponse>;

  deleteTask(
    request: task_pb.TaskRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: task_pb.TaskResponse) => void): grpcWeb.ClientReadableStream<task_pb.TaskResponse>;

  deleteTask(
    request: task_pb.TaskRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: task_pb.TaskResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/TaskService/DeleteTask',
        request,
        metadata || {},
        this.methodDescriptorDeleteTask,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/TaskService/DeleteTask',
    request,
    metadata || {},
    this.methodDescriptorDeleteTask);
  }

}

