/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.2
// source: user.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as user_pb from './user_pb'; // proto import: "user.proto"


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorLoginUser = new grpcWeb.MethodDescriptor(
    '/UserService/LoginUser',
    grpcWeb.MethodType.UNARY,
    user_pb.UserRequest,
    user_pb.UserResponse,
    (request: user_pb.UserRequest) => {
      return request.serializeBinary();
    },
    user_pb.UserResponse.deserializeBinary
  );

  loginUser(
    request: user_pb.UserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<user_pb.UserResponse>;

  loginUser(
    request: user_pb.UserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_pb.UserResponse) => void): grpcWeb.ClientReadableStream<user_pb.UserResponse>;

  loginUser(
    request: user_pb.UserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_pb.UserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/UserService/LoginUser',
        request,
        metadata || {},
        this.methodDescriptorLoginUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/UserService/LoginUser',
    request,
    metadata || {},
    this.methodDescriptorLoginUser);
  }

  methodDescriptorRegisterUser = new grpcWeb.MethodDescriptor(
    '/UserService/RegisterUser',
    grpcWeb.MethodType.UNARY,
    user_pb.UserRequest,
    user_pb.UserResponse,
    (request: user_pb.UserRequest) => {
      return request.serializeBinary();
    },
    user_pb.UserResponse.deserializeBinary
  );

  registerUser(
    request: user_pb.UserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<user_pb.UserResponse>;

  registerUser(
    request: user_pb.UserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_pb.UserResponse) => void): grpcWeb.ClientReadableStream<user_pb.UserResponse>;

  registerUser(
    request: user_pb.UserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_pb.UserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/UserService/RegisterUser',
        request,
        metadata || {},
        this.methodDescriptorRegisterUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/UserService/RegisterUser',
    request,
    metadata || {},
    this.methodDescriptorRegisterUser);
  }

}

